# Server Configuration
spring.profiles.active=dev

# Mail Configuration
spring.mail.host=server17213-10344.hostycare.online
spring.mail.port=465
spring.mail.username=noreply@townseva.in
spring.mail.password=Bbd@14151994
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.starttls.enable=false

# Database Configuration
spring.datasource.username=nagar_dev
spring.sql.init.mode=always
spring.datasource.password=DevPass@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
# Flyway Migration
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update


# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Custom Properties
app.jwt.secret=9a4f2c8d3b7a1e6f4g5h8i0j2k4l6m8n0p2q4r6s8t0u2v4x6z8
app.jwt.expiration-ms=3153600000000


# Twilio Configuration
twilio.account_sid=AC349613979568d34da4845c4a4d28f13d
twilio.auth_token=ea718eeea53c3c746007655e9f22d3f0
twilio.phone_number=+14155238886

# Whatsapp Provider Setup (twilio / wabridge / meta)
whatsapp.provider=wabridge
whatsapp.wabridge.api.url=https://api.wabridge.com/v1/messages
whatsapp.wabridge.app_key=538eeb71-eee7-4fde-b5c4-e7c70c57b72b
whatsapp.wabridge.api.key=83847d3d23d9e61e51ee098a71f6ad0404e0507d45a04543c4
whatsapp.wabridge.verify_token=loknagar_wa_secret_2026

# Whatsapp API
whatsapp.api.url=https://graph.facebook.com/v17.0
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
